

services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    networks:
      - Expense-app
    ports:
      - "8000:8000"
    environment:
      SPRING_DATABASE_URL: "jdbc:mysql://mysql_db:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATABASE_USERNAME: "root"
      SPRING_DATABASE_PASSWORD: "kangnaAman"
    depends_on:
      - mysql_db
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  mysql_db:
    image: mysql
    container_name: mysql
    networks:
      - Expense-app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "kangnaAman"
      MYSQL_DATABASE: "expenses_tracker"
    restart: always 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pkangnaAman"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  Expense-app:
    driver: bridge
